console.log("Starting")
console.log("      *  ***** ")
console.log("      * *     *")
console.log("      * *      ")
console.log("      *  ***** ")
console.log("*     *       *")
console.log("*     * *     *")
console.log(" *****   ***** ")
